---
# This workflow uses Zig to cross-compile to multiple non-Linux platforms.
name: zig cross-compile other

"on": [push, pull_request]

jobs:
  build:
    name: >-
      ${{ matrix.ttriple }} ${{ matrix.linkage }} thr:${{ matrix.threads }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        zig_version: ["0.17.0"]
        ttriple:
          - aarch64-freebsd-none
          - aarch64-maccatalyst-none
          - aarch64-macos-none
          - aarch64-netbsd-none
          - aarch64-openbsd-none
          - aarch64-windows-gnu
          - aarch64_be-netbsd-none
          - arm-freebsd-eabihf
          - arm-netbsd-eabi
          - arm-netbsd-eabihf
          - arm-openbsd-eabi
          - armeb-netbsd-eabi
          - armeb-netbsd-eabihf
          - m68k-netbsd-none
          - mips-netbsd-eabi
          - mips-netbsd-eabihf
          - mips64-openbsd-none
          - mips64el-openbsd-none
          - mipsel-netbsd-eabi
          - mipsel-netbsd-eabihf
          - powerpc-netbsd-eabihf
          - powerpc-openbsd-eabihf
          - powerpc64-freebsd-none
          - powerpc64-openbsd-none
          - powerpc64le-freebsd-none
          - riscv32-netbsd-none
          - riscv64-freebsd-none
          - riscv64-netbsd-none
          - riscv64-openbsd-none
          - sparc64-netbsd-none
          - sparc64-openbsd-none
          - thumb-windows-gnu
          - wasm32-wasi-musl
          - x86-freebsd-none
          - x86-netbsd-none
          - x86-openbsd-none
          - x86-windows-gnu
          - x86_64-dragonfly
          - x86_64-freebsd-none
          - x86_64-haiku
          - x86_64-maccatalyst-none
          - x86_64-macos-none
          - x86_64-netbsd-none
          - x86_64-openbsd-none
          - x86_64-serenity
          - x86_64-windows-gnu
        cplusplus: [true]
        linkage: [static, dynamic]
        threads: [false, true]
        exclude:
          - threads: true
            ttriple: wasm32-wasi-musl
          # FIXME: Recompile with -fPIC
          - linkage: dynamic
            ttriple: wasm32-wasi-musl
          # FIXME: No available compatible targets
          - ttriple: m68k-netbsd-none
          # FIXME: Unknown target CPU `generic`
          - ttriple: sparc-netbsd-none
          # FIXME: Unable to provide libc
          - ttriple: x86_64-dragonfly
          - ttriple: x86_64-haiku
          - ttriple: x86_64-serenity

    steps:
      - uses: actions/checkout@v7

      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig_version }}

      - name: Build
        run: >
          zig build
          -Dtarget=${{ matrix.ttriple }}
          -Dlinkage=${{ matrix.linkage }}
          -Denable_cplusplus=${{ matrix.cplusplus }}
          -Denable_threads=${{ matrix.threads }}
          -Denable_werror
